# FOrmualtion and solving of the optimization problem

In [1]:
import numpy as np
from scipy.optimize import minimize

def euclidean_distance(p1, p2):
    return np.linalg.norm(p2 - p1)

def objective_mindist(coordinates):
    distances = []
    for i in range(N):
        for j in range(i + 1, N):
            distances.append(euclidean_distance(coordinates[i], coordinates[j]))
    return -min(distances)

def objective_logsum(coordinates):
    result = np.infty
    sum = 0 
    for i in range(N):
        for j in range(N):
            if i!=j:
                sum += np.exp(
                    -betta * euclidean_distance(coordinates[i], coordinates[j])            
                    )
                
    result = -np.log(sum)/betta
    return -result

def constraint_sum_to_one(coordinates):
    # print(np.sum(coordinates, axis=0)/N - 1)
    return np.sum(coordinates, axis=0)/N - 1

def constraint_sum_to_one_vector(coordinates):
    A = np.kron(np.identity(N),np.ones((1,3)))
    return np.dot(A, coordinates)-1

# Betta factor of log-sum-exponential function (Monteiro, 2014)
betta = 1

N = 4  # Number of points

# Initial guess for coordinates
# initial_guess = np.ones((N, 3)) / 3
initial_guess = np.random.rand(N,3)
# initial_guess = np.array(
#    [[0.99, 0.01, 0.01], [0.01, 0.99, 0.01], [0.01, 0.01, 0.99], [1/3, 1/3, 1/3]]
#    )

# Constraints
constraints = [
    {'type': 'eq', 'fun': constraint_sum_to_one_vector},
    {'type': 'ineq', 'fun': lambda x: x}
]

# Bounds for each variable (xi, yi, zi > 0)
bounds = [(0, None), (0, None), (0, None)] * N

# Solve the optimization problem
result = minimize(
    objective_logsum, 
    initial_guess.flatten(), 
    method='SLSQP', 
    bounds=bounds, 
    constraints=constraints
    )

# Reshape the result to get the optimal coordinates
optimal_coordinates = result.x.reshape(N, 3)

# Print the optimal coordinates and the optimal value
print("Initial Guess")
print(initial_guess)
print("Optimal Coordinates:")
print(optimal_coordinates)
print("Optimal Minimum Pairwise Distance:", -result.fun)


Initial Guess
[[0.47249466 0.39827229 0.30350129]
 [0.21264238 0.35955621 0.40802687]
 [0.20783491 0.72321019 0.05482299]
 [0.2939758  0.75942976 0.16590028]]
Optimal Coordinates:
[[8.77965077e-01 1.22034923e-01 6.17995238e-18]
 [2.42861287e-17 4.75764670e-01 5.24235330e-01]
 [2.12545545e-01 7.27920827e-01 5.95336289e-02]
 [2.20873856e-01 6.86327812e-01 9.27983314e-02]]
Optimal Minimum Pairwise Distance: -2.09705161866968
