# FOrmualtion and solving of the optimization problem

In [23]:
import numpy as np
from scipy.optimize import minimize

def euclidean_distance(p1, p2):
    return np.linalg.norm(p2 - p1)

def objective(coordinates):
    distances = []
    for i in range(N):
        for j in range(i + 1, N):
            distances.append(euclidean_distance(coordinates[i], coordinates[j]))
    return -min(distances)

def constraint_sum_to_one(coordinates):
    # print(np.sum(coordinates, axis=0)/N - 1)
    return np.sum(coordinates, axis=0)/N - 1

def constraint_sum_to_one_vector(coordinates):
    A = np.kron(np.identity(N),np.ones((1,3)))
    return np.dot(A, coordinates)-1

N = 4  # Number of points

# Initial guess for coordinates
# initial_guess = np.ones((N, 3)) / 3
initial_guess = np.random.rand(N,3)
# initial_guess = np.array(
#    [[0.99, 0.01, 0.01], [0.01, 0.99, 0.01], [0.01, 0.01, 0.99], [1/3, 1/3, 1/3]]
#    )

# Constraints
constraints = [
    {'type': 'eq', 'fun': constraint_sum_to_one_vector},
    {'type': 'ineq', 'fun': lambda x: x}
]

# Bounds for each variable (xi, yi, zi > 0)
bounds = [(0, None), (0, None), (0, None)] * N

# Solve the optimization problem
result = minimize(objective, initial_guess.flatten(), method='SLSQP', bounds=bounds, constraints=constraints)

# Reshape the result to get the optimal coordinates
optimal_coordinates = result.x.reshape(N, 3)

# Print the optimal coordinates and the optimal value
print("Initial Guess")
print(initial_guess)
print("Optimal Coordinates:")
print(optimal_coordinates)
print("Optimal Minimum Pairwise Distance:", -result.fun)


Initial Guess
[[0.03916012 0.59296454 0.9486537 ]
 [0.61871866 0.34338068 0.21444109]
 [0.15735123 0.33335182 0.15643246]
 [0.98961743 0.26109127 0.59310178]]
Optimal Coordinates:
[[3.33333328e-01 1.04388193e-18 6.66666672e-01]
 [1.00000000e+00 6.06344116e-19 3.20114779e-19]
 [2.74972731e-01 4.50973315e-01 2.74053954e-01]
 [6.98257825e-01 4.56732877e-11 3.01742175e-01]]
Optimal Minimum Pairwise Distance: 0.33333332839498
